#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

my $nas=`/etc/scripts/inputIP`;
chomp($nas);


my $oid         = ".1.3.6.1.4.1.14179.2.1.7.1";
my @snmpIPinfo  = `/usr/bin/snmpwalk -v 2c -c public $nas $oid`;

my @APMacRogue = grep{/(3.6.1.4.1.14179.2.1.7.1.1\.)/} @snmpIPinfo;
my @APMacRogues = `echo '@APMacRogue' | cut -d ':' -f2`;

print @APMacRogues;

#my @APSSID = grep{/(3.6.1.4.1.14179.2.1.7.1.11\.)/} @snmpIPinfo;
#my @APSSIDs = `echo '@APSSID' | cut -d '"' -f2`;

#my @StartTime = grep{/(3.6.1.4.1.14179.2.1.7.1.3\.)/} @snmpIPinfo;
#my @StartTimes = `echo '@StartTime' | cut -d '"' -f2`;

#my @LastTime = grep{/(3.6.1.4.1.14179.2.1.7.1.4\.)/} @snmpIPinfo;
#my @LastTimes = `echo '@LastTime' | cut -d '"' -f2`;

