#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

#my $nas = '192.168.1.2';
my $nas=`/etc/scripts/inputIP`;
chomp($nas);

my @MAClist = `/usr/bin/snmpwalk -v 2c -c public $nas .1.3.6.1.4.1.14179.2.1.4.1.1 | cut -d ' ' -f1`;
my @MACDeclist;

my $plimit = scalar(@MAClist);

for (my $p =0 ; $p < $plimit ; $p++)
{
        $MACDeclist[$p] = substr("$MAClist[$p]",30);
}

#print @MACDeclist;
my $i=0;
my @IPs;
my @usernames;
my @MACs;
my @ssids;
my @APMacs;

foreach my $MACDec (@MACDeclist){


my $IP	 =".1.3.6.1.4.1.14179.2.1.4.1.2.$MACDec"; #$bsnMobileStationIpAddress 

print $IP;
$IPs[$i] = `/usr/bin/snmpwalk -v 2c -c public $nas $IP | cut -d ':' -f2`;

#my $username = ".1.3.6.1.4.1.14179.2.1.4.1.3.$MACDec";
#$usernames[$i] = `/usr/bin/snmpwalk -v 2c -c public $nas $username | cut -d '"' -f2`;


#my $Ssid = ".1.3.6.1.4.1.14179.2.1.4.1.7.$MACDec"; #bsnMobileStationSsid
#$ssids[$i] = `/usr/bin/snmpwalk -v 2c -c public $nas $Ssid | cut -d '"' -f2 `;

#my $APMacAddress= ".1.3.6.1.4.1.14179.2.1.4.1.4"; #bsnMobileStationAPMacAddr
#$APMacs[$i] = `/usr/bin/snmpwalk -v 2c -c public $nas $APMacAddress | cut -d ':' -f2`;
#$i++;
}

#print @IPs;

