#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;


my $nas=`/etc/scripts/inputIP`;
chomp($nas);

my $IP	 =".1.3.6.1.4.1.14179.2.1.4.1.2"; #$bsnMobileStationIpAddress 
my @IPs = `/usr/bin/snmpwalk -v 2c -c public $nas $IP | cut -d ' ' -f4`;

my $MAC =  ".1.3.6.1.4.1.14179.2.1.4.1.1"; #bsnMobileStationMacAddress
my @MACs = `/usr/bin/snmpwalk -v 2c -c public $nas $MAC | cut -d ':' -f2`;



my $lim = scalar(@IPs);

for(my $i=0 ; $i < $lim; $i++){
	chomp($IPs[$i]);
	chomp($MACs[$i]);
 	print "$IPs[$i] met MAC : $MACs[$i]\n"; 
}

