#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
use Redis::Client;
my $client = Redis::Client->new( host => 'localhost', port => 6379 );

$client->del('iphashes');

#my $nas = '192.168.1.2';
my $nas=`/etc/scripts/inputIP`;
chomp($nas);


my @MAClist = `/usr/bin/snmpwalk -v 2c -c public $nas .1.3.6.1.4.1.14179.2.1.4.1.1 | cut -d ' ' -f1`;
my @MACDeclist;

my $plimit = scalar(@MAClist);
for (my $p =0 ; $p < $plimit ; $p++)
{


        $MACDeclist[$p] = substr("$MAClist[$p]",30);

}


print @MACDeclist;



