#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
use Redis::Client;
my $client = Redis::Client->new( host => 'localhost', port => 6379 );

$client->del('iphashes');

#my $nas = '192.168.1.2';
my $nas=`/etc/scripts/inputIP`;
chomp($nas);

my $IP	 =".1.3.6.1.4.1.14179.2.1.4.1.2"; #$bsnMobileStationIpAddress 
my @IPs = `/usr/bin/snmpwalk -v 2c -c public $nas $IP | cut -d ' ' -f4`;

my $username = ".1.3.6.1.4.1.14179.2.1.4.1.3";
my @usernames = `/usr/bin/snmpwalk -v 2c -c public $nas $username | cut -d '"' -f2`;

my $MAC =  ".1.3.6.1.4.1.14179.2.1.4.1.1"; #bsnMobileStationMacAddress
my @MACs = `/usr/bin/snmpwalk -v 2c -c public $nas $MAC | cut -d ':' -f2`;

my $Ssid = ".1.3.6.1.4.1.14179.2.1.4.1.7"; #bsnMobileStationSsid
my @ssids = `/usr/bin/snmpwalk -v 2c -c public $nas $Ssid |cut -d '"' -f2 `;

my $APMacAddress= ".1.3.6.1.4.1.14179.2.1.4.1.4"; #bsnMobileStationAPMacAddr
my @APMacs = `/usr/bin/snmpwalk -v 2c -c public $nas $APMacAddress | cut -d ':' -f2`;

my $APName = ".1.3.6.1.4.1.14179.2.2.1.1.3"; #bsnAPName
my @APNames = `/usr/bin/snmpwalk -v 2c -c public $nas $APName |cut -d '"' -f2 `;

my $APDot3MacAddress = ".1.3.6.1.4.1.14179.2.2.1.1.1"; # bsnAPDot3MacAddress
my @APDot3Macs = `/usr/bin/snmpwalk -v 2c -c public $nas $APDot3MacAddress |cut -d ':' -f2 `;

my $end = scalar(@APNames);

my %hashAP;
for(my $j=0;$j< $end; $j++){
	chomp($APDot3Macs[$j]);
	chomp($APNames[$j]);
	$hashAP{$APDot3Macs[$j]} = "$APNames[$j]";
}


my $limit = scalar(@IPs);
my $values;
my $nameAP; 

for(my $i=0 ; $i < $limit ; $i++) {


	if ($IPs[$i]  ne "") {
		chomp($IPs[$i]);}
	if ($usernames[$i] ne ""){
		chomp($usernames[$i]);}
	if ($MACs[$i] ne ""){
		chomp($MACs[$i]);}
	if ($ssids[$i] ne ""){
		chomp($ssids[$i]);}
	if($APMacs[$i] ne ""){
		chomp($APMacs[$i]);
	$nameAP =$hashAP{$APMacs[$i]};
	chomp($nameAP);
	}

	$values ="$IPs[$i],$usernames[$i],$MACs[$i],$ssids[$i],$APMacs[$i],$nameAP";
	$client->hset('iphashes', $IPs[$i] => $values);
}


