#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
use Redis::Client;
my $client = Redis::Client->new( host => 'localhost', port => 6379 );

my @keys = $client->hkeys( 'aphashes' );

print "<script src='sorttable.js'></script>";
print "<div class='row'>";
print "<div class='col-md-12'>";
print  "<table class='sortable table table-striped'>";
print "<tr>\n";
print "<th>APNaam</th>\n";
print "<th>Grafiek \#users</th>\n";
print "<th>Grafiek detailled</th>\n";
print "<th>2.4GHz</th>\n";
print "<th>5GHz</th>\n";
print "<th>Total</th>\n";
print "<th>Locatie</th>\n";
print "<th class='sorttable_nosort'>IP AP</th>";
print "<th>MAC AP</th>";
print "</tr>\n";

my $key;
my $temp;
my $total;
my $total24;
my $total5;

foreach $key (@keys){  # key = APname


my $values = $client->hget( 'aphashes', $key );
my @value=  split /,/, $values;


#$values= "$APNames[$i],$MACAPS[$i],$usersperap[$j],$usersperap[$j+1],$locations[$i],$ipforAP[$i]";
	print "\n";
        print "<tr>";
        print "<td> <a href='/monitoring/toonclientsperap.php?AP=$value[0]'>$value[0]</td>";
        print "<td> <a href='/munin/WLC/WLC/snmp_wlc_ap_$value[0]_bsnApIfNoOfUsers.html'> Grafiek \#Users</td>";
        print "<td> <a href='/munin/WLC/WLC/snmp_wlc_ap_$value[0]_bsnAPIfLoad.html'> Grafiek Detailed</td>";
        print "<td>$value[2]</td>";
        print "<td>$value[3]</td>";
        $temp = $value[2] + $value[3];
        $total = $total + $temp;
        $total24 = $total24 + $value[2];
        $total5 = $total5 + $value[3];

        print "<td>$temp</td>";
        print "<td>$value[4]</td>";
        print "<td>$value[5]</td>";
        print "<td>$value[1]</td>";
        print "</tr>";


}

#my $limit = scalar(@snmpgetinfoAPName);

#for(my $i=0 ; $i < $limit ; $i++) {
#	$j = ($i*2);
#	chomp($snmpgetinfoAPName[$i]);
#	chomp($usersperap[$i]);
#	print "\n";
#	print "<tr>";
#	print "<td> <a href='/monitoring/toonclientsperap.php?AP=$snmpgetinfoAPName[$i]'>$snmpgetinfoAPName[$i]</td>";
#	print "<td> <a href='/munin/WLC/WLC/snmp_wlc_ap_$snmpgetinfoAPName[$i]_bsnApIfNoOfUsers.html'> Grafiek $snmpgetinfoAPName[$i] No Of Users</td>";
#	print "<td> <a href='/munin/WLC/WLC/snmp_wlc_ap_$snmpgetinfoAPName[$i]_bsnAPIfLoad.html'> Grafiek $snmpgetinfoAPName[$i] Detailed</td>";
#	print "<td>$usersperap[$j]</td>";
#	print "<td>$usersperap[$j+1]</td>";
#	$temp = $usersperap[$j+1] + $usersperap[$j];
#	$total = $total + $temp;
#	$total24 = $total24 + $usersperap[$j];
#	$total5 = $total5 + $usersperap[$j+1];

#	print "<td>$temp</td>";
#	print "<td>$snmplocationsAP[$i]</td>";
#	print "<td>$ipforAP[$i]</td>";
#	print "<td>$snmpgetinfoMACAP[$i]</td>";
#	print "</tr>";
#}

print "<tfoot><tr><td><h3>Totaal</h3></td><td></td><td></td><td><h3>$total24</h3></td><td><h3>$total5</h3></td><td><h3>$total</h3></td><td></td><tr></tfoot>";
print "\n</table></div></div>\n";
print "</body>\n";
print "</html>\n";

