#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;


my $total = `/etc/scripts/cache/ToonOverzichtIP | grep -c $ARGV[0]`;
if($total == 1){
print "<h4>Er is in 1 resultaat: </h4>";
}else{

print "<h4>Er zijn in $total resultaten: </h4>";
}
my $lines = `/etc/scripts/cache/ToonOverzichtIP | grep $ARGV[0]`;
print $lines;
