#!/usr/bin/perl

# 01/03/2015
# Dit script genereert een overzicht van alle rogues (met gegevens : IP,username,MAC,SSID,...)
# (voorbeeld http://193.191.187.33/monitoring/overviewrogues.php)
# Om het overzicht te tonen worden alle gegevens uit de cache gehaald ( hash 'roguehashes) die er d.m.v. het script RogueInfoincache ingestoken zijn.
# @keysbackup wordt gebruikt tijdens de update van de cache, zodat er gedurende de update geen lege pagina getoond wordt, vanaf dat roguehashes 
# geupdate is, wordt de backuphash (roguehashesbackup) verwijderd en iphashes gebruikt.
use diagnostics;
use strict;
use warnings;
use Redis::Client;

my $client = Redis::Client->new( host => 'localhost', port => 6379 ); # Connectie Redis
my @keys = $client->hkeys( 'roguehashes' ); 

my $hash="roguehashes";
my @keys = $client->hkeys( 'roguehashes' );# standaard worden de keys van roguehashes opgehaald
my @keysbackup = $client->hkeys( 'roguehashesbackup' );# keys uit iphashesbackup ophalen (indien ze niet bestaan is @keysbackup leeg)


if(@keysbackup){#als er een backup bestaat -> update is bezig  -> gebruik de backup
	@keys = @keysbackup;
	$hash = "roguehashesbackup";
}

# hoofdingen tabel + sorteerbaar + zoekbalkje
print "<div class='form-group'>";
print "<label>Zoeken in de tabel</label>";
print "<input type='text' class='form-control' id='search' placeholder='Typ simpele zoektermen om te zoeken in de tabel.'>";
print "</div>";
print "<script src='sorttable.js'></script>";
print "<div class='row'>";
print "<div class='col-md-12'>";
print  "<table id='table' class='sortable table table-striped'>";
print "<tr>\n";
print "<th>AP MAC Address</th>\n";
print "<th class='sorttable_alpha'>SSID</th>";
print "<th class='sorttable_nosort'>First Time Reported</th>";
print "<th class='sorttable_nosort'>Last Time Reported</th>";
print "</tr>\n";

# elke waarde in de cache wordt in de tabel gestoken.
my $key;
foreach $key (@keys){  


my $values = $client->hget( $hash, $key ); # key = MAC AP
my @value=  split /,/, $values;  # values gesplit op ","

	print "\n";
	print "<tr>";
	print "<td>$value[0]</td>";
	print "<td>$value[1]</td>";
	print "<td>$value[2]</td>";
	print "<td>$value[3]</td>";
	print "</tr>";
}

print "\n</table></div></div>\n";
print "</body>\n";
print "</html>\n";

print "<script src='search.js'></script>";

