#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

my $ssids = '.1.3.6.1.4.1.14179.2.1.1.1.2';
my $mobileStations = '.1.3.6.1.4.1.14179.2.1.1.1.38';

my @ssidlist = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 $ssids | cut -d '"' -f2`;
my @usersperssid = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 $mobileStations | cut -d " " -f4 `;

my $limit = scalar(@ssidlist);

if ($ARGV[0] && $ARGV[0] eq "config") {
print "graph_title WLC connected stations per SSID\n";
print "graph_args --base 1000 -l 0\n";
print "graph_vlabel station count\n";
print "graph_scale no\n";
print "graph_category Swag\n";



for (my $i=0 ; $i < $limit ; $i++)
{
	chomp($ssidlist[$i]);
	chomp($usersperssid[$i]);
#	print "$ssidlist[$i] : $usersperssid[$i]\n";
	
	print "$ssidlist[$i].label $ssidlist[$i]\n";
    	print "$ssidlist[$i].info users connected to $ssidlist[$i]\n";  
    	print "$ssidlist[$i].min 0\n";
	exit;

}

}

for (my $j=0 ; $j < $limit ;$j++)
{
        chomp($ssidlist[$j]);
        chomp($usersperssid[$j]);

	print "$ssidlist[$j].value " . "$usersperssid[$j]" . "\n";
	

}
