#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
my $nas=`/etc/scripts/inputIP`;
chomp($nas);
my $ssids = '.1.3.6.1.4.1.14179.2.1.1.1.2';
my $mobileStations = '.1.3.6.1.4.1.14179.2.1.1.1.38';

my @ssidlist = `/usr/bin/snmpwalk -v 2c -c public $nas $ssids | cut -d '"' -f2`;
my @usersperssid = `/usr/bin/snmpwalk -v 2c -c public $nas $mobileStations | cut -d " " -f4 `;


my $limit = scalar(@ssidlist);

if ($ARGV[0] && $ARGV[0] eq "config") {

print "graph_title Clients per SSID\n";
print "graph_args --base 1000 -l 0\n";
print "graph_vlabel clients\n";
print "graph_scale no\n";
print "graph_category WLC\n";


	for (my $i=0 ; $i < $limit ; $i++)
	{
		chomp($ssidlist[$i]);
		chomp($usersperssid[$i]);

		my $ssid= lc($ssidlist[$i]);
		print "$ssid.label $ssidlist[$i]\n";
    		print "$ssid.info users connected to $ssidlist[$i]\n";  
		print "$ssid.draw AREA\n";
		print "$ssid.min 0\n";
	}
exit;
}

for (my $j=0 ; $j < $limit ;$j++)
{
        chomp($ssidlist[$j]);
        chomp($usersperssid[$j]);
	my $ssidlc= lc($ssidlist[$j]);
	print "$ssidlc.value " . "$usersperssid[$j]" . "\n";
}
