#!/bin/bash
nas="192.168.1.2"
if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

bsnAPName='.1.3.6.1.4.1.14179.2.2.1.1.3';

if [ "$1" = "config" ]; then
    echo 'graph_title WLC connected access points'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel AP count'
    echo 'graph_scale no'
    echo 'graph_category WLC'
    echo 'ap_count.label AP count'
    echo 'ap_count.info Total connected access points'
    echo 'ap_count.min 0'

    exit 0
fi

/usr/bin/snmpwalk -v 2c -c public $nas $bsnAPName 2>/dev/null | wc -l | awk '{print "ap_count.value " $1}'
