#!/usr/bin/perl 
use diagnostics;
use strict;
use warnings;

my $nas=`/etc/scripts/inputIP`;
chomp($nas);
my $rogues  = '.1.3.6.1.4.1.14179.2.1.7.1.11';

my $rogueslistcount = `/usr/bin/snmpwalk -v 2c -c public $nas $rogues | wc -l`;
my @rogueslist = `/usr/bin/snmpwalk -v 2c -c public $nas $rogues`;


if ($ARGV[0] && $ARGV[0] eq "config") {

	print "graph_title Total rogue access points\n";
	print "graph_args --base 1000 -l 0\n";
	print "graph_vlabel rogueap count\n";
	print "graph_scale no\n";
	print "graph_category WLC\n";
	
	print "rogueap_count.label Rogue count\n";
        print "rogueap_count.info users Total rogues\n";
        print "rogueap_count.draw AREA\n";
        print "rogueap_count.min 0\n";
	exit;
}

print "rogueap_count.value " . "$rogueslistcount" . "\n";
