#!/bin/bash

nas=`/etc/scripts/inputIP`


ls /etc/munin/plugins | grep -P "snmp_wlc_ap_.*(bsnApIfNoOfUsers|bsnAPIfLoad)" | xargs -i rm /etc/munin/plugins/{}
#/usr/bin/snmpwalk -v 2c -c public $nas 1.3.6.1.4.1.14179.2.2.1.1.3 | cut -d '"' -f2 | xargs -i ln -s /usr/share/muni$
/usr/bin/snmpwalk -v 2c -c public $nas 1.3.6.1.4.1.14179.2.2.1.1.3 | cut -d '"' -f2 | xargs -i ln -s /usr/share/mun$
/etc/init.d/munin-node restart


