#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

my $dot11a=0;
my $dot11b=0;
my $dot11g=0;
my $unknown=0;
my $mobile=0;

my $outputSNMP= `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 1.3.6.1.4.1.14179.2.1.4.1.25`;
my @lines = split /\n/, $outputSNMP;
my $counter = 0;
if($counter != $#lines +1){
	print ($#lines +1);
	if( grep( /[1]$/, @lines ) ){
		$dot11a++;
	}
        elsif( grep( /[2]$/, @lines ) ){
                $dot11b++;
        }
        elsif( grep( /[3]$/, @lines ) ){
                $dot11g++;
	}
        elsif( grep( /[4]$/, @lines ) ){
                $unknown++;
        }
 	elsif( grep( /[1]$/, @lines ) ){
                $mobile++;
        }
  $counter++;
  print "$counter \n";
}


