#!/bin/bash
# Dit script zorgt ervoor dat onze machine van buitenaf bereikbaar blijft bij reboot 

ip route del default via 192.168.1.1
ip route add default via 193.191.187.62
echo nameserver 8.8.8.8 >> /etc/resolv.conf
