#!/bin/bash

# Dit scriptje zorgt ervoor dat je gemakkelijk het IP van de WLC kunt veranderen. In elk script waar er een SNMPget/walk uitgevoerd wordt 
# zal dit script opgeroepen worden om het IP-adres te bepalen. Om het IP te veranderen, vervang je het huidige IP in het echo-statement.

echo "10.25.0.5"; 	#WLC UCCL
#echo "192.168.1.2"; 	#WLC
