#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;


my $code = ".1.3.6.1.4.1.14179.2.2.1.1.1";
my @snmpgetinfo = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 $code | cut -d ':' -f2`;
print "@snmpgetinfo";





