#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
use Switch;


#ophalen van Mac-adressen clients om om te zetten naar MACDec
my @MAClist = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 .1.3.6.1.4.1.14179.2.1.4.1.1 | cut -d ' ' -f1`;
my @MACDeclist;

my $plimit = scalar(@MAClist);
for (my $p =0 ; $p < $plimit ; $p++)
{

        $MACDeclist[$p] = substr("$MAClist[$p]",30);

}


print @MACDeclist;

