#!/bin/bash
# Dit script dient om munin te restarten, dit hebben we vooral gebruikt in de beginfase van ons project. 
service munin-node restart
echo "munin-node restart : ok"
service apache2 restart
echo "apache2 restart: ok"
 
/etc/init.d/munin stop
/etc/init.d/munin start
echo "munin restart : ok"
 

