#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
my $nas=`/etc/scripts/inputIP`;
chomp($nas);

my $shitload   =".1.3.6.1.4.1.14179.2";  
my @snmpgetinfoShitload = `/usr/bin/snmpwalk -v 2c -c public $nas $shitload`;

print @snmpgetinfoShitload;
