#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

my $nas=`/etc/scripts/inputIP`;
chomp($nas);
my $APName = undef;
my $action = undef;
my $ApMacDec = `/usr/bin/snmpwalk -v 2c -c public 10.25.0.5 .1.3.6.1.4.1.14179.2.2.1.1.3 | perl -ne 'print \$1 if /.+14179.2.2.1.1.3.(.+) =.+$APName\"/'`;
my $bsnAPGroupVlanName  = ".1.3.6.1.4.1.14179.2.2.1.1.30.$ApMacDec";
my $snmpgetinfo = `/usr/bin/snmpget -v 2c -c public 10.25.0.5 $bsnAPGroupVlanName`;
print "$snmpgetinfo\n";
$bsnAPGroupVlanName = $snmpgetinfo =~ s/.+: "(.*)"\n/$1/r;
