#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;


use Redis::Client;
my $client = Redis::Client->new( host => 'localhost', port => 6379 );


# work with hashes

my $ip = "192.168.1.1";

my $values = " a4:45:ed:45:85 username lol";


$client->hset( 'iphashes', $ip => $values );
my $hash_val = $client->hget( 'iphashes', $ip );
print "$hash_val\n";      
