#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;


use Redis::Client;
my $client = Redis::Client->new( host => 'localhost', port => 6379 );


# work with hashes


my $values = "lol,lol,lol,lol,lol,olo,lol,lolo,lololo,lool,lolol,lolo";

for (my $i=0 ; $i < 5 ; $i++)
{
my $ip = $i;



$client->hset( 'iphashes', $ip => $values );
}


$client->hset( 'iphashesbackup', olo => $values );
