#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

print "<div class='row'>";
print "<div class='col-md-12'>";
print  "<table class='table table-striped'>";
print "<tr>\n";
print "<th>IP-address</th>\n";
print "<th>Username</th>\n";
print "<th>MAC-address </th>\n";
print "<th>SSID</th>\n";
print "<th>MAC-AP (Base Radio MAC)</th>\n";
print "<th>APName</th>\n";
print "</tr>\n";

my $lines = `/etc/scripts/cache/ToonAlgemeenOverzichtCache | grep $ARGV[0]`;

print $lines;
print "\n</table></div></div>\n";

