#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

#my $nas ="192.168.1.2";
my $nas=`/etc/scripts/inputIP`;
chomp($nas);

my $IP	 =".1.3.6.1.4.1.14179.2.1.4.1.2"; #$bsnMobileStationIpAddress 
my @snmpgetinfoIP = `/usr/bin/snmpwalk -v 2c -c public $nas $IP | cut -d ' ' -f4`;

#print @snmpgetinfoIP;

my $username = ".1.3.6.1.4.1.14179.2.1.4.1.3";
my @snmpgetinfoUsername = `/usr/bin/snmpwalk -v 2c -c public $nas $username | cut -d '"' -f2`;

my $MAC =  ".1.3.6.1.4.1.14179.2.1.4.1.1"; #bsnMobileStationMacAddress
my @snmpgetinfoMAC = `/usr/bin/snmpwalk -v 2c -c public $nas $MAC | cut -d ':' -f2`;

#print @snmpgetinfoMAC;

my $Ssid = ".1.3.6.1.4.1.14179.2.1.4.1.7"; #bsnMobileStationSsid
my @snmpgetinfoSsid = `/usr/bin/snmpwalk -v 2c -c public $nas $Ssid |cut -d '"' -f2 `;

#print @snmpgetinfoAPSsid;

my $APMacAddress= ".1.3.6.1.4.1.14179.2.1.4.1.4"; #bsnMobileStationAPMacAddr
my @snmpgetinfoAPMacAddress = `/usr/bin/snmpwalk -v 2c -c public $nas $APMacAddress | cut -d ':' -f2`;

# dit is het Base Radio MAC
#  bsnAPDot3MacAddress	1.3.6.1.4.1.14179.2.2.1.1.1   vergelijken hiermee en zo de APname bepalen?
#Test voor het weergeven van AP Name
my $APName = ".1.3.6.1.4.1.14179.2.2.1.1.3"; #bsnAPName
my @snmpAPName = `/usr/bin/snmpwalk -v 2c -c public $nas $APName |cut -d '"' -f2 `;

my $APDot3MacAddress = ".1.3.6.1.4.1.14179.2.2.1.1.1"; # bsnAPDot3MacAddress
my @snmpDot3MacAddress = `/usr/bin/snmpwalk -v 2c -c public $nas $APDot3MacAddress |cut -d ':' -f2 `;

my $end = scalar(@snmpAPName);

my %hashAP;
for(my $j=0;$j< $end; $j++){
	chomp($snmpDot3MacAddress[$j]);
	chomp($snmpAPName[$j]);
	$hashAP{$snmpDot3MacAddress[$j]} = "$snmpAPName[$j]";
}

print "<script src='sorttable.js'></script>";
print "<div class='row'>";
print "<div class='col-md-12'>";
print "<table class='sortable table table-striped'>";
print "<tr>\n";
print "<th>test</th>\n";
print "<th class='sorttable_nosort'>IP-address</th>\n";
print "<th>Name</th>\n";
print "<th>MAC-address </th>";
print "<th>SSID</th>";		
print "<th>MAC-AP (Base Radio MAC)</th>";
print "<th>APName</th>";		
print "</tr>";

my $limit = scalar(@snmpgetinfoIP);
#my $limit1 = scalar(@snmpgetinfoUsername);
#my $limit2 = scalar(@snmpgetinfoUsername)
#my $limit3 = scalar(@snmpgetinfoMAC);
#my $limit4 = scalar(@snmpgetinfoSsid);
#my $limit5 = scalar(@snmpgetinfoAPMacAddress);
#my $limit6 = scalar(@hashAP);

#print "echo $limit $limit1 $limit2 $limit3 $limit4 $limit5 $limit6";

for(my $i=0 ; $i < $limit ; $i++) {
	
	chomp($snmpgetinfoIP[$i]);
	chomp($snmpgetinfoUsername[$i]);
	chomp($snmpgetinfoMAC[$i]);
	chomp($snmpgetinfoSsid[$i]);
	chomp($snmpgetinfoAPMacAddress[$i]);
		
	print "\n";
	print "<tr>";
	print "<td>$i</td>";
	print "<td><a href='/monitoring/toonipinfo.php?IP=$snmpgetinfoIP[$i]'>$snmpgetinfoIP[$i]</a></td>";
	print "<td> $snmpgetinfoUsername[$i] </td>";
	print "<td> $snmpgetinfoMAC[$i] </td>";
	print "<td><a href='/monitoring/toonclientsperssid.php?SSID=$snmpgetinfoSsid[$i]'>$snmpgetinfoSsid[$i]</a></td>";
	print "<td>$snmpgetinfoAPMacAddress[$i]</td>";
	print "<td> <a href='/monitoring/toonclientsperap.php?AP=$hashAP{$snmpgetinfoAPMacAddress[$i]}'>$hashAP{$snmpgetinfoAPMacAddress[$i]}</td>";
	print "</tr>";
}

print "\n</table></div></div>\n";
#print "</body>\n";
#print "</html>\n";

