#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;
my $nas=`/etc/scripts/inputIP`;
chomp($nas);

my $IP	 =".1.3.6.1.4.1.14179.2.1.4.1.2"; #$bsnMobileStationIpAddress 
my @snmpgetinfoIP = `/usr/bin/snmpwalk -v 2c -c public $nas $IP | cut -d ' ' -f4`;

#print @snmpgetinfoIP;

my $MAC =  ".1.3.6.1.4.1.14179.2.1.4.1.1"; #bsnMobileStationMacAddress
my @snmpgetinfoMAC = `/usr/bin/snmpwalk -v 2c -c public $nas $MAC | cut -d ':' -f2`;

#print @snmpgetinfoMAC;

my $Ssid = ".1.3.6.1.4.1.14179.2.1.4.1.7"; #bsnMobileStationSsid
my @snmpgetinfoSsid = `/usr/bin/snmpwalk -v 2c -c public $nas $Ssid |cut -d '"' -f2 `;

#print @snmpgetinfoAPSsid;

my $APMacAddress= ".1.3.6.1.4.1.14179.2.1.4.1.4"; #bsnMobileStationAPMacAddr
my @snmpgetinfoAPMacAddress = `/usr/bin/snmpwalk -v 2c -c public $nas $APMacAddress | cut -d ':' -f2`;

# dit is het Base Radio MAC
#  bsnAPDot3MacAddress	1.3.6.1.4.1.14179.2.2.1.1.1   vergelijken hiermee en zo de APname bepalen?
#Test voor het weergeven van AP Name
my $APName = ".1.3.6.1.4.1.14179.2.2.1.1.3"; #bsnAPName
my @snmpAPName = `/usr/bin/snmpwalk -v 2c -c public $nas $APName |cut -d '"' -f2 `;

my $APDot3MacAddress = ".1.3.6.1.4.1.14179.2.2.1.1.1"; # bsnAPDot3MacAddress
my @snmpDot3MacAddress = `/usr/bin/snmpwalk -v 2c -c public $nas $APDot3MacAddress |cut -d ':' -f2 `;

my $end = scalar(@snmpAPName);

my %hashAP;
for(my $j=0;$j< $end; $j++){
	chomp($snmpDot3MacAddress[$j]);
	chomp($snmpAPName[$j]);
	$hashAP{$snmpDot3MacAddress[$j]} = "$snmpAPName[$j]";
}

my $protocol= ".1.3.6.1.4.1.14179.2.1.4.1.25" ; #bsnMobileStationProtocol 
my @snmpgetinfoProtocol = `/usr/bin/snmpwalk -v 2c -c public $nas $protocol | cut -d ' ' -f4`;


my $bytesreceived = ".1.3.6.1.4.1.14179.2.1.6.1.2";
my @snmpgetinfoBytesReceived = `/usr/bin/snmpwalk -v 2c -c public $nas $bytesreceived | cut -d ':' -f2`;
#print "@snmpgetinfoBytesReceived";

my $bytessent = ".1.3.6.1.4.1.14179.2.1.6.1.2";
my @snmpgetinfoBytesSent = `/usr/bin/snmpwalk -v 2c -c public $nas $bytessent | cut -d ':' -f2`;
#print "@snmpgetinfoBytesSent";


# om een overzicht te maken
# -> $snmpgetinfoIP $snmpgetinfoAPSsid $snmpgetinfoAPMacAddress omzetten in array 
# for loop 

#HTML probeersel

#print "<!DOCTYPE html>\n";
#print "<html>\n";
#print "<body>\n";
print "<div class='row'>";
print "<div class='col-md-12'>";
print  "<table class='table table-striped'>";
print "<tr>\n";
print "<th>IP-address</th>\n";
print "<th>MAC-address </th>\n";
print "<th>SSID</th>\n";		
print "<th>MAC-AP (Base Radio MAC)</th>\n";
print "<th>APName</th>\n";		
print "</tr>\n";

my $limit = scalar(@snmpgetinfoIP);


for(my $i=0 ; $i < $limit ; $i++) {
	
	chomp($snmpgetinfoIP[$i]);
	chomp($snmpgetinfoMAC[$i]);
	chomp($snmpgetinfoSsid[$i]);
	chomp($snmpgetinfoAPMacAddress[$i]);
	
	print "\n";
	print "<tr>";
	print "<td><a href='/monitoring/toonipinfo.php?IP=$snmpgetinfoIP[$i]'>$snmpgetinfoIP[$i]</a></td>";
	print "<td> $snmpgetinfoMAC[$i] </td>";
	print "<td><a href='/monitoring/toonclientsperssid.php?SSID=$snmpgetinfoSsid[$i]'>$snmpgetinfoSsid[$i]</a></td>";
	print "<td>$snmpgetinfoAPMacAddress[$i]</td>";
	print "<td> <a href='/monitoring/toonclientsperap.php?AP=$hashAP{$snmpgetinfoAPMacAddress[$i]}'>$hashAP{$snmpgetinfoAPMacAddress[$i]}</td>";
	print "</tr>";
}

print "\n</table></div></div>\n";
#print "</body>\n";
#print "</html>\n";

