#!/usr/bin/perl
# 01/03/2016
# Dit is een oud script en is vervangen door ToonOverzichtAPsCache (in /etc/scripts/cache)

# In dit script wordt alle info opgehaald d.m.v. SNMPwalks en in arrays gestoken en afgeprint d.m.v. een for-loop.
# Deze aanpak is fout en genereert dus een foutief overzicht wanneer er APs wegvallen of bijkomen.

use diagnostics;
use strict;
use warnings;

my $nas=`/etc/scripts/inputIP`;
chomp($nas);
my $APName = ".1.3.6.1.4.1.14179.2.2.1.1.3"; 	#bsnAPName
my @snmpgetinfoAPName = `/usr/bin/snmpwalk -v 2c -c public $nas $APName | cut -d '"' -f2`;

my $MACAP = ".1.3.6.1.4.1.14179.2.2.1.1.1"; #bsnAPDot3MacAddress
my @snmpgetinfoMACAP = `/usr/bin/snmpwalk -v 2c -c public $nas $MACAP | cut -d ':' -f2`;

my $NuOfClientsAP = ".1.3.6.1.4.1.14179.2.2.2.1.15"; #bsnAPIfLoadNumOfClients
my @usersperap = `/usr/bin/snmpwalk -v 2c -c public $nas $NuOfClientsAP | cut -d " " -f4 `;

my $location= ".1.3.6.1.4.1.14179.2.2.1.1.4"; # bsnAPLocation
my @snmplocationsAP = `/usr/bin/snmpwalk -v 2c -c public $nas $location | cut -d '"' -f2`;

my $ip= "1.3.6.1.4.1.14179.2.2.1.1.28";
my @ipforAP = `/usr/bin/snmpwalk -v 2c -c public $nas $ip | cut -d ':' -f2`;

# hoofdingen tabel + sorteerbaar
print "<script src='sorttable.js'></script>";
print "<div class='row'>";
print "<div class='col-md-12'>";
print  "<table class='sortable table table-striped table-responsive table-condensed'>";
print "<tr>\n";
print "<th>APNaam</th>\n";
print "<th>Grafiek</th>\n";
print "<th>Grafiek gedetailleerd</th>\n";
print "<th>2.4 GHz</th>\n";
print "<th>5 GHz</th>\n";
print "<th>Total</th>\n";
print "<th>Locatie</th>\n";
print "<th class='sorttable_nosort'>Ip Address AP</th>";
print "<th>MAC Address AP</th>";
print "</tr>\n";
my $total24 = 0;
my $total5 = 0;
my $total = 0;
my $limit = scalar(@snmpgetinfoAPName);

my $j=0;
my $temp = 0;
for(my $i=0 ; $i < $limit ; $i++) {
	$j = ($i*2);
	chomp($snmpgetinfoAPName[$i]);
	chomp($usersperap[$i]);
	print "\n";
	print "<tr>";
	print "<td> <a href='/monitoring/toonclientsperap.php?AP=$snmpgetinfoAPName[$i]'>$snmpgetinfoAPName[$i]</td>";
	print "<td> <a href='/munin/WLC/WLC/snmp_wlc_ap_$snmpgetinfoAPName[$i]_bsnApIfNoOfUsers.html'> Grafiek $snmpgetinfoAPName[$i] No Of Users</td>";
	print "<td> <a href='/munin/WLC/WLC/snmp_wlc_ap_$snmpgetinfoAPName[$i]_bsnAPIfLoad.html'> Grafiek $snmpgetinfoAPName[$i] Detailed</td>";
	print "<td>$usersperap[$j]</td>";
	print "<td>$usersperap[$j+1]</td>";
	$temp = $usersperap[$j+1] + $usersperap[$j];
	$total = $total + $temp;
	$total24 = $total24 + $usersperap[$j];
	$total5 = $total5 + $usersperap[$j+1];

	print "<td>$temp</td>";
	print "<td>$snmplocationsAP[$i]</td>";
	print "<td>$ipforAP[$i]</td>";
	print "<td>$snmpgetinfoMACAP[$i]</td>";
	print "</tr>";
}

print "<tfoot><tr><td><h3>Totaal</h3></td><td></td><td></td><td><h3>$total24</h3></td><td><h3>$total5</h3></td><td><h3>$total</h3></td><td></td><tr></tfoot>";
print "\n</table></div></div>\n";
print "</body>\n";
print "</html>\n";

