#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;

print "<!DOCTYPE html>\n";
print "<html>\n";
print "<body>\n";
print "<table border='1' style='width:100%'>\n";
print "<tr>\n";
print "<td>SSID-Name</td>\n";
print "</tr>\n";

my $Ssid = ".1.3.6.1.4.1.14179.2.1.4.1.7"; 
my @snmpgetinfoSsid = uniq(`/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 $Ssid |cut -d '"' -f2 `);
my $limit = scalar(@snmpgetinfoSsid);


for(my $i=0 ; $i < $limit ; $i++) {


 	print "<tr>";
	print "<td><a href='/toonclientsperssid.php?SSID=$snmpgetinfoSsid[$i]'>$snmpgetinfoSsid[$i]</a></td>";
	print "</tr>";

}

print "\n</table>\n";
print "</body>\n";
print "</html>\n";


sub uniq {
    my %seen;
    grep !$seen{$_}++, @_;
}

