#!/usr/bin/perl
use diagnostics;
use strict;
use warnings;



my $APName = ".1.3.6.1.4.1.14179.2.2.1.1.3"; 	#bsnAPName
my @snmpgetinfoAPName = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 $APName | cut -d '"' -f2`;

my $MACAP = ".1.3.6.1.4.1.14179.2.2.1.1.1"; #bsnAPDot3MacAddress
my @snmpgetinfoMACAP = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 $MACAP | cut -d '"' -f2`;


print "<!DOCTYPE html>\n";
print "<html>\n";
print "<body>\n";
print "<table border='1' style='width:100%'>\n";
print "<tr>\n";
print "<td>APName</td>\n";
print "</tr>\n";

my $limit = scalar(@snmpgetinfoAPName);


for(my $i=0 ; $i < $limit ; $i++) {
	
	chomp($snmpgetinfoAPName[$i]);
	
	print "\n";
	print "<tr>";
	print "<td> <a href='/toonclientsperap.php?AP=$snmpgetinfoAPName[$i]'>$snmpgetinfoAPName[$i]</td>";
	print "</tr>";
}

print "\n</table>\n";
print "</body>\n";
print "</html>\n";

