#!/bin/bash

if [ "$1" = "autoconf" ]; then
    echo yes
    exit 0
fi

if [ "$1" = "config" ]; then
    echo 'graph_title WLC connected stations per SSID'
    echo 'graph_args --base 1000 -l 0'
    echo 'graph_vlabel station count'
    echo 'graph_scale no'
    echo 'graph_category WLC'

    echo 'khleuven.label khleuven'
    echo 'khleuven.info \# users connected to khleuven'
    echo 'khleuven.min 0'

    echo 'help.label khleuven-wifi-help'
    echo 'help.info \# users connected to khleuven-wifi-help'
    echo 'help.min 0'

    echo 'eduroam.label eduroam'
    echo 'eduroam.info \# users connected to eduroam'
    echo 'eduroam.min 0'

    echo 'guest.label khleuven-wifi-guest'
    echo 'guest.info \# users connected to khleuven-wifi-guest'
    echo 'guest.min 0'

    exit 0
fi

/usr/bin/snmpwalk -v 2c -c public 10.25.0.5 1.3.6.1.4.1.14179.2.1.1.1.38 2>/dev/null | perl -ple 's/(SNMPv2-SMI::enterprises|iso.3.6.1.4.1).14179.2.1.1.1.38\.//; s/= Counter32://; s/^1 /khleuven.value/; s/^3 /help.value/; s/^4 /eduroam.value/; s/^5 /guest.value/;'
