#!/usr/bin/perl 
use diagnostics;
use strict;
use warnings;

#iso.3.6.1.4.1.14179.2.2.1.1.3.0.31.158.65.226.224 = STRING: "Pippin"
#iso.3.6.1.4.1.14179.2.2.1.1.3.0.33.85.172.200.160 = STRING: "Merry"


my $apnames = `/usr/bin/snmpwalk -v 2c -c public 192.168.1.2 .1.3.6.1.4.1.14179.2.2.1.1.3`;
my @splitted = split /"/,$apnames;


my $limit = scalar(@splitted)-1;

for (my $i =1 ; $i < $limit ;$i = $i+2){
	print $splitted[$i];
	print "\n";

}
