#!/usr/bin/php
<?php
if( isset( $_SERVER['argv'][1] ) && $_SERVER['argv'][1] == 'config' ) {
?>
graph_category test
graph_title Hello World!
graph_vlabel important value
graph_total total
rn1.label First random number
rn2.label Second random number
<?php
	exit(0);
}
printf( "rn1.value %s\n", rand(0,100) );
printf( "rn2.value %s\n", rand(0,100) );

?>
